### ISSUE TITLE
[1.12.2] Crash on Creative Tabs scrolling

### ISSUE THREAD

**Issue by Krutoy242** [AHilyard/ItemBorders#33]
Happen to one of [E2EE](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) player - he was tabulating between creative tabs and when get to the page 20, game crashed:

```ruby
NullPointerException: Rendering screen
    at com.anthonyhilyard.itemborders.util.Selectors.itemMatches(Selectors.java:85)
    at com.anthonyhilyard.itemborders.config.ItemBordersConfig.getBorderColorForItem(ItemBordersConfig.java:214)
    at com.anthonyhilyard.itemborders.ItemBorders.render(ItemBorders.java:61)
    at com.anthonyhilyard.itemborders.ItemBorders.renderBorder(ItemBorders.java:41)
    at net.minecraft.client.gui.inventory.GuiContainer.handler$zzg000$drawSlotItemBorders(GuiContainer.java:784)
```

### https://mclo.gs/Oc4anIW

I am developer of E2EE and can't reproduce it, but I though it would be worth to mention.
![javaw_RR3kScf3qK](https://github.com/user-attachments/assets/b1d5ec4b-5a20-4c99-9ffc-a4e904f81158)

**Comment by AHilyard** [comment]
This issue has been moved to discord: https://discord.gg/UCKjnamDaW
I am much more active there, and it should get more attention there. Thank you for understanding.
