### ISSUE TITLE
Crashes on 1.19.3 Fabric

### ISSUE THREAD

**Issue by EGOIST1372** [AHilyard/ItemBorders#7]
Hi
I know the latest version is 1.19.2 but I just wanted to try it on 1.19.3 and give feedback
love your mods
thanks in advance <3 

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-01-15 15:35:28
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_1159 net.minecraft.class_4587$class_4665.method_23761()'
	at com.anthonyhilyard.itemborders.ItemBorders.render(ItemBorders.java:67)
	at com.anthonyhilyard.itemborders.ItemBorders.renderBorder(ItemBorders.java:39)
	at net.minecraft.class_329.handler$chf001$renderSlot(class_329.java:6994)
	at net.minecraft.class_329.method_1762(class_329.java:1261)
	at net.minecraft.class_329.method_1759(class_329.java:581)
	at net.minecraft.class_329.mixinextras$bridge$fb9e2989-2c93-4ab4-a0ee-6427a6de419f$method_1759(class_329.java)
	at net.minecraft.class_329.wrapOperation$bpk000$if$Batching(class_329.java:1545)
	at net.minecraft.class_329.method_1753(class_329.java:207)
	at net.minecraft.class_757.method_3192(class_757.java:910)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.anthonyhilyard.itemborders.ItemBorders.render(ItemBorders.java:67)
	at com.anthonyhilyard.itemborders.ItemBorders.renderBorder(ItemBorders.java:39)
	at net.minecraft.class_329.handler$chf001$renderSlot(class_329.java:6994)
	at net.minecraft.class_329.method_1762(class_329.java:1261)
	at net.minecraft.class_329.method_1759(class_329.java:581)
	at net.minecraft.class_329.mixinextras$bridge$fb9e2989-2c93-4ab4-a0ee-6427a6de419f$method_1759(class_329.java)
	at net.minecraft.class_329.wrapOperation$bpk000$if$Batching(class_329.java:1545)
	at net.minecraft.class_329.method_1753(class_329.java:207)
Mixins in Stacktrace: None found

-- Affected level --
Details:
	All players: 1 total; [class_746[''/165, l='ClientLevel', x=88.16, y=27.00, z=-81.61]]
	Chunk stats: 1024, 665
	Level dimension: minecraft:overworld
	Level spawn location: World: (144,64,-192), Section: (at 0,0,0 in 9,4,-12; chunk contains blocks 144,-64,-192 to 159,319,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 2234677 game time, 415253 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace: None found

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, itemswapper/default, file/itemframes-e700.zip, file/XeKr+flowers+leaves+model+pack+modified.zip, file/VanillaTweaks_1.19.3.zip, file/VIllagerAndOthersCloakFix.zip, file/Luminous1.3.zip, file/Kubban's Saplings, file/Flower_Golems_v1.zip, file/Flower_Crowns_(1.18)_v2.zip, file/Desert_Bloom-v1.0.2.zip, file/Butterflies+-+Mrblueyeti.zip, file/Better+sheep+-+Mrblueyeti.zip, file/Better_Chickens_V1.3.zip, file/Better_Dogs-Shiba_Inu.zip, loadmyresources.hiddenpack, replaymod_lang

**Comment by EGOIST1372** [comment]
with new update it works with 1.19.3
thanks so much <3
